"""SSH config generation: pinned host keys, no AutoAddPolicy."""
import os
import shlex
import shutil
import stat
import subprocess
from pathlib import Path


DML_PREFIX = "dml-"

# Files in ~/.ssh that belong to the dml-ssh tool itself and must never be
# treated as stale identity keys.
_MANAGED_NON_KEY_NAMES = {"dml-config", "dml-config.tmp"}


def is_managed_alias(token: str) -> bool:
    """True if an SSH Host token was generated by dml-ssh (``dml-...``)."""
    return token.startswith(DML_PREFIX)


def ensure_key(path: Path) -> Path:
    path = Path(path)
    pub = path.with_suffix(path.suffix + ".pub") if path.suffix else Path(str(path) + ".pub")
    if path.exists() and pub.exists():
        return pub
    path.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(["ssh-keygen", "-t", "ed25519", "-N", "", "-f", str(path)], check=True)
    os.chmod(path, 0o600)
    return pub


def snippet(alias, info, key_path, pub_path, scheduler):
    # Absolute proxy path: VS Code / GUI shells run with a minimal PATH
    # (/usr/bin:/bin) where a conda-managed dml-ssh is not found. Embedding
    # the resolved path keeps ProxyCommand working without manual symlinks.
    exe = shutil.which("dml-ssh") or "dml-ssh"
    proxy = f"{exe} proxy --runtime {info['runtime_id']} --generation {info.get('ssh_generation', info['generation'])} --public-key {shlex.quote(str(pub_path))}"
    return "\n".join([
        f"Host {alias}",
        f"    HostName {alias}",
        "    User dml",
        f"    IdentityFile {key_path}",
        "    IdentitiesOnly yes",
        "    StrictHostKeyChecking yes",
        f"    ProxyCommand {proxy}",
        "",
    ])


def write_snippet(out: Path, alias, snippet_text, prune_managed: bool = True) -> int:
    """Write ``alias`` block to ``out``, erasing stale dml-ssh blocks.

    Every ``dml-ssh configure <runtime>`` replaces the previous runtime's
    config so VS Code Remote-SSH only ever lists a single ``dml-*`` host.
    Unrelated (non ``dml-``) hosts and global directives are preserved.

    Returns the number of stale ``dml-*`` host blocks removed.
    """
    out = Path(out)
    out.parent.mkdir(parents=True, exist_ok=True)
    existing = out.read_text() if out.exists() else ""
    lines = existing.splitlines(keepends=True)
    kept: list[str] = []
    removed = 0
    dropping = False  # inside a stale dml-* block
    for line in lines:
        stripped = line.strip()
        if stripped.lower().startswith("host ") and len(stripped.split()) > 1:
            tokens = stripped.split()[1:]
            managed = [t for t in tokens if is_managed_alias(t)]
            if prune_managed and managed:
                if alias in tokens:
                    # Same-host idempotent replacement: drop silently, not stale.
                    dropping = True
                    continue
                rest = [t for t in tokens if not is_managed_alias(t)]
                removed += len(managed)
                if rest:
                    # Mixed `Host dml-old myhost`: keep user's host, drop ours.
                    indent = line[: len(line) - len(line.lstrip())]
                    kept.append(f"{indent}Host {' '.join(rest)}\n")
                    dropping = False
                else:
                    dropping = True
                continue
            dropping = False
            kept.append(line)
            continue
        if dropping:
            # Skip option/body lines of the stale block (indented or blank).
            # A non-indented, non-Host directive ends the block; keep it.
            if not stripped or line.startswith((" ", "\t")):
                continue
            dropping = False
            kept.append(line)
            continue
        kept.append(line)
    if snippet_text and not snippet_text.endswith("\n"):
        snippet_text += "\n"
    kept.append(snippet_text)
    tmp = out.with_suffix(".tmp")
    tmp.write_text("".join(kept))
    os.chmod(tmp, 0o600)
    tmp.replace(out)
    return removed


def write_known_host(info, host_key, prune_managed: bool = True) -> int:
    """Pin ``alias`` host key, erasing stale ``dml-`` entries.

    Returns the number of stale entries removed.
    """
    kh = Path.home() / ".ssh" / "known_hosts"
    try:
        alias = f"dml-{info['runtime_id']}-g{info.get('ssh_generation', info['generation'])}"
        existing = kh.read_text() if kh.exists() else ""
        kept: list[str] = []
        removed = 0
        for line in existing.splitlines():
            first = line.split()[0] if line.split() else ""
            # known_hosts host field may be comma-separated; drop the line if
            # any entry is managed (ours) and it is not the new alias.
            hosts = first.split(",")
            if prune_managed and any(is_managed_alias(h) for h in hosts):
                if first == alias or (len(hosts) == 1 and hosts[0] == alias):
                    continue  # same alias: replaced below
                removed += 1
                continue
            if line.startswith(alias + " ") or line == alias:
                continue  # same alias: replaced below
            kept.append(line)
        kept.append(f"{alias} {host_key.strip()}")
        kh.parent.mkdir(parents=True, exist_ok=True)
        kh.write_text("\n".join(kept) + "\n")
        os.chmod(kh, 0o600)
        return removed
    except Exception:
        return 0


def prune_old_keys(keep_path: Path) -> list[Path]:
    """Delete stale ``dml-*`` identity keys next to ``keep_path``.

    Never touches ``dml-config*`` or the key currently in use (private + .pub).
    Returns the list of removed files.
    """
    removed: list[Path] = []
    try:
        keep_path = Path(keep_path)
        parent = keep_path.parent
        if not parent.exists():
            return removed
        keep_names = {keep_path.name, keep_path.name + ".pub", str(keep_path) + ".pub"}
        # also keep the derived .pub name when keep_path already ends with .pub
        for child in parent.glob(f"{DML_PREFIX}*"):
            if not child.is_file():
                continue
            if child.name in _MANAGED_NON_KEY_NAMES:
                continue
            if child.name.startswith("dml-config"):
                continue
            if child.name in keep_names:
                continue
            # Only prune key-like files: `dml-*` with no suffix or `.pub`,
            # never configs, known_hosts, or unrelated dotfiles.
            if child.suffix not in ("", ".pub"):
                continue
            try:
                child.unlink()
                removed.append(child)
            except Exception:
                continue
    except Exception:
        pass
    return removed
