import { useEffect, useRef, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import * as monaco from 'monaco-editor';
import { Terminal } from '@xterm/xterm';
import { FitAddon } from '@xterm/addon-fit';
import '@xterm/xterm/css/xterm.css';
import { interactive, type Runtime, type Workspace } from '../services/interactive';
import { WorkspaceConnection } from '../services/workspaceProtocol';

type Entry = { name: string; type: string };
type Tab = { path: string; content: string; version: string; dirty: boolean };

export default function InteractiveEditor() {
  const { id } = useParams(); const [workspace, setWorkspace] = useState<Workspace | null>(null); const [runtime, setRuntime] = useState<Runtime | null>(null);
  const [entries, setEntries] = useState<Entry[]>([]); const [tabs, setTabs] = useState<Tab[]>([]); const [active, setActive] = useState(''); const [status, setStatus] = useState('Connecting…'); const [error, setError] = useState('');
  const connection = useRef<WorkspaceConnection | null>(null); const editorNode = useRef<HTMLDivElement>(null); const terminalNode = useRef<HTMLDivElement>(null); const editor = useRef<monaco.editor.IStandaloneCodeEditor | null>(null); const terminal = useRef<Terminal | null>(null); const activePath = useRef('');
  const current = tabs.find(tab => tab.path === active);
  const refresh = async () => { if (!connection.current) return; const value = await connection.current.request('list', ''); setEntries((value.entries as Entry[]) ?? []); };
  useEffect(() => { let disposed = false; let resize: ResizeObserver | undefined; const load = async () => { try {
    const [item, running] = await Promise.all([interactive.detail(id!), interactive.runtime(id!)]); if (disposed) return; if (!running?.editor_capable || running.state !== 'READY' || running.desired_state !== 'RUNNING') throw new Error('This runtime does not support the workspace editor. Start a new editor-capable runtime.'); setWorkspace(item); setRuntime(running);
    const grant = await interactive.workspaceConnection(running.id); if (disposed) return; const stream = new WorkspaceConnection(grant); connection.current = stream; stream.onState = state => setStatus(String(state.state ?? 'Workspace state changed')); await stream.connect(); if (disposed) return; setStatus('Connected'); await refresh();
    if (!editorNode.current || !terminalNode.current) return;
    const instance = monaco.editor.create(editorNode.current, { value: '', language: 'plaintext', theme: 'vs-dark', automaticLayout: true, minimap: { enabled: false }, readOnly: false, lineNumbers: 'on' }); editor.current = instance;
    instance.onDidChangeModelContent(() => { const path = activePath.current; if (!path) return; setTabs(all => all.map(tab => tab.path === path ? { ...tab, content: instance.getValue(), dirty: true } : tab)); });
    const term = new Terminal({ convertEol: true, scrollback: 5000, fontSize: 13 }); const fit = new FitAddon(); term.loadAddon(fit); term.open(terminalNode.current); fit.fit(); terminal.current = term; stream.onPtyOutput = bytes => term.write(bytes); stream.onPtyExit = () => setStatus('Shell exited · choose New Terminal'); term.onData(data => stream.ptyInput(data)); resize = new ResizeObserver(() => { fit.fit(); stream.resize(term.cols, term.rows); }); resize.observe(terminalNode.current); stream.openPty(term.cols, term.rows);
  } catch (reason) { if (!disposed) { setError(reason instanceof Error ? reason.message : 'Editor unavailable'); setStatus('Disconnected'); } } }; void load(); return () => { disposed = true; resize?.disconnect(); editor.current?.dispose(); terminal.current?.dispose(); connection.current?.close(); connection.current = null; }; }, [id]);
  const open = async (path: string) => { try { const value = await connection.current!.request('read', path); const tab = { path, content: String(value.content ?? ''), version: String(value.version ?? ''), dirty: false }; setTabs(all => [...all.filter(item => item.path !== path), tab]); activePath.current = path; setActive(path); editor.current?.setValue(tab.content); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not open file'); } };
  const select = (path: string) => { const tab = tabs.find(item => item.path === path); if (!tab) return; activePath.current = path; setActive(path); editor.current?.setValue(tab.content); };
  const save = async (tab = current) => { if (!tab?.dirty) return; try { const value = await connection.current!.write(tab.path, editor.current?.getValue() ?? tab.content, tab.version); setTabs(all => all.map(item => item.path === tab.path ? { ...item, content: editor.current?.getValue() ?? item.content, version: String(value.version ?? item.version), dirty: false } : item)); setStatus('Written to workspace · save a revision to keep it after Stop'); } catch (reason) { setError(reason instanceof Error ? `${reason.message}: reload the file before overwriting` : 'Save failed'); } };
  const saveAll = async () => { for (const tab of tabs.filter(item => item.dirty)) await save(tab); };
  return <div className="workspace-editor"><header><Link to={`/interactive/${id}`}>Workspace details</Link><span>{workspace?.name}</span><span>Revision {workspace?.revision.revision_number}</span><span>{runtime?.state.toLowerCase()}</span><span role="status">{status}</span><button className="btn btn-secondary" onClick={() => void saveAll()}>Save All</button><button className="btn btn-secondary" disabled title="Durable snapshot publishing is not yet available on this deployment">Save for Later</button><button className="btn btn-secondary" disabled title="Training handoff is not yet available on this deployment">Submit for Training</button></header>{error && <p role="alert">{error}</p>}<aside><button onClick={() => void refresh()}>Refresh</button><p>Files</p>{entries.map(entry => <button className="file-entry" key={entry.name} disabled={entry.type !== 'file'} onClick={() => void open(entry.name)}>{entry.type === 'directory' ? '▸ ' : ''}{entry.name}</button>)}</aside><main><nav>{tabs.map(tab => <button key={tab.path} className={active === tab.path ? 'active-tab' : ''} onClick={() => select(tab.path)}>{tab.dirty ? '● ' : ''}{tab.path}</button>)}</nav><div className="monaco-host" ref={editorNode} /><section className="terminal-panel"><div><span>Terminal</span><button onClick={() => terminal.current && connection.current?.openPty(terminal.current.cols, terminal.current.rows)}>New Terminal</button></div><div ref={terminalNode} /></section></main></div>;
}
