import os
import json
import shlex
import shutil
import logging
import subprocess
import tempfile
import time
import uuid
import docker

from config import (
    OUTPUT_DIR, VRAM_ESTIMATION_SCRIPT, DOCKER_HUB_USERNAME,
    CONTAINER_OUTPUT_MOUNT, CONTAINER_AS_ROOT,
)
from api import SchedulerAPI
from object_store import ObjectStore
from output_monitor import META_FILE, OutputFileMonitor, write_baseline, load_baseline
from telemetry import record_job, record_event
from job_state import load_running_job, save_running_job, clear_running_job
from hardware import get_gpu_info
import runtime_config

logger = logging.getLogger("executor")


def _docker_host_path(path: str) -> str:
    """Normalize a host path for use in a `docker run -v` / `docker cp` spec.

    Docker for Windows accepts Windows-style paths but prefers forward slashes;
    normalizing avoids backslash escaping issues in the CLI. On POSIX the path
    is returned unchanged.
    """
    if os.name == "nt":
        return path.replace("\\", "/")
    return path


class JobExecutor:
    def __init__(self, api: SchedulerAPI):
        self.api = api
        try:
            self.docker_client = docker.from_env()
        except Exception as e:
            logger.error("Failed to connect to Docker daemon: %s", e)

    @staticmethod
    def _record_job(job_id: str, image_name: str, flag: str, status: str,
                    started_at: float, vram_estimate_gb: float = 0.0):
        job_type = "estimation" if flag == "vram_estimation" else "training"
        record_job({
            "id": job_id,
            "image": image_name,
            "type": job_type,
            "status": status,
            "vramEstimateGb": vram_estimate_gb,
            "startedAt": time.strftime("%H:%M:%S", time.localtime(started_at)),
            "durationSec": int(time.time() - started_at),
        })
        record_event(
            "success" if status == "completed" else "error",
            f"Job {job_id} ({job_type}) {status}",
        )

    def pull_docker_image(self, image_name: str) -> bool:
        logger.info("Pulling Docker image: %s", image_name)
        try:
            self.docker_client.images.pull(image_name)
            logger.info("Successfully pulled image: %s", image_name)
            return True
        except Exception as e:
            logger.error("Failed to pull image %s: %s", image_name, e)
            return False

    def _image_workdir(self, image_name: str) -> str | None:
        """Return the image's configured WORKDIR, or None if it can't be read."""
        try:
            image = self.docker_client.images.get(image_name)
            return (image.attrs.get("Config", {}) or {}).get("WorkingDir") or None
        except Exception as e:
            logger.debug("Failed to read WORKDIR for %s: %s", image_name, e)
            return None

    def _resolve_mount_target(self, image_name: str) -> str | None:
        """Container path to mount the job output dir at (the image's WORKDIR),
        or None when it can't be used (WORKDIR is empty or root fs)."""
        workdir = self._image_workdir(image_name) or "/workspace"
        if workdir in ("", "/"):
            logger.warning(
                "Refusing to mount output dir over root fs; "
                "falling back to %s", CONTAINER_OUTPUT_MOUNT,
            )
            return None
        return workdir

    def _prepare_output_mount(self, job_output_dir: str,
                              image_name: str) -> tuple[str, set[str]]:
        """Make the host output dir behave as the container's working directory.

        Seeds the output dir with the image's WORKDIR contents and returns the
        container path to mount it at, so anything the container writes relative
        to its working directory lands in <OUTPUT_DIR>/<job_id> regardless of
        what the user's code writes. Falls back to the conventional
        CONTAINER_OUTPUT_MOUNT mount if the workdir can't be prepared.

        The second return value is the baseline set of absolute file paths that
        existed after seeding (i.e. the image's baked-in files); the output
        monitor uses it to skip those files so only files generated by the
        running code are uploaded to the object store.
        """
        workdir = self._resolve_mount_target(image_name)
        if workdir is None:
            return CONTAINER_OUTPUT_MOUNT, set()

        seed_name = f"seed-{uuid.uuid4().hex[:12]}"
        try:
            subprocess.run(
                ["docker", "create", "--name", seed_name, image_name],
                check=True, capture_output=True, text=True,
            )
            subprocess.run(
                ["docker", "cp", f"{seed_name}:{workdir}/.",
                 _docker_host_path(job_output_dir)],
                check=True, capture_output=True, text=True,
            )
            logger.info("Seeded %s with %s WORKDIR contents (%s)",
                        job_output_dir, image_name, workdir)
        except subprocess.CalledProcessError as e:
            logger.warning("Failed to seed output dir from %s: %s",
                           image_name, e.stderr.strip())
            return CONTAINER_OUTPUT_MOUNT, set()
        finally:
            subprocess.run(
                ["docker", "rm", "-f", seed_name],
                capture_output=True, text=True,
            )

        baseline = set()
        for root, _dirs, files in os.walk(job_output_dir):
            for name in files:
                baseline.add(os.path.join(root, name))
        write_baseline(job_output_dir, baseline)
        baseline.add(os.path.join(job_output_dir, META_FILE))
        return workdir, baseline

    @staticmethod
    def _container_user_args() -> list[str]:
        """Run containers as the worker's UID/GID so files written into the
        output mount are owned by the worker (readable for upload, deletable
        on cleanup). Falls back to root (no args) when CONTAINER_AS_ROOT=1.

        Passing a numeric --user only makes sense on POSIX hosts; under Docker
        Desktop on Windows the container's root maps back to the host user, so
        we skip the flag there (os.getuid/getgid don't exist on Windows).
        """
        if CONTAINER_AS_ROOT:
            return []
        if os.name != "posix" or not hasattr(os, "getuid"):
            return []
        return [
            "--user", f"{os.getuid()}:{os.getgid()}",
            "-e", "HOME=/tmp",
        ]

    @staticmethod
    def _parse_python_command(command: str) -> list[str] | None:
        """Extract purely the python execution arguments from a command string."""
        try:
            command_args = json.loads(command) if command.lstrip().startswith("[") else shlex.split(command)
        except (json.JSONDecodeError, ValueError):
            return None

        for index, value in enumerate(command_args):
            if os.path.basename(value).startswith("python"):
                command_args = command_args[index + 1:]
                while command_args and command_args[0].startswith("-"):
                    command_args.pop(0)
                return command_args or None
        return None

    def handle_vram_estimation(self, job_id: str, image_name: str, command: str):
        started_at = time.time()
        target_command = self._parse_python_command(command)
        if not target_command:
            logger.error("Job %s needs a Python command for VRAM estimation.", job_id)
            self._record_job(job_id, image_name, "vram_estimation", "failed", started_at)
            self.api.mark_job_failed(
                job_id, "user", "Job needs a Python command for VRAM estimation"
            )
            return

        with tempfile.TemporaryDirectory(prefix=f"vram_{job_id}_") as report_dir:
            report_path = os.path.join(report_dir, "report.json")
            cmd = [
                "docker", "run", "--rm", "--gpus", "all",
                "--name", f"vram-{uuid.uuid4().hex[:12]}",
                "-v", f"{_docker_host_path(VRAM_ESTIMATION_SCRIPT)}:/vram_estimation.py:ro",
                "-v", f"{_docker_host_path(report_dir)}:/report",
                "--entrypoint", "python", image_name,
                "/vram_estimation.py", "--output", "/report/report.json", *target_command,
            ]
            
            logger.info("Running VRAM estimation for job %s.", job_id)
            record_event("info", f"Job {job_id} VRAM estimation started")
            try:
                result = subprocess.run(cmd, capture_output=True, text=True)
            except Exception as e:
                logger.error("Failed to run VRAM estimation for job %s: %s", job_id, e)
                self._record_job(job_id, image_name, "vram_estimation", "failed", started_at)
                self.api.mark_job_failed(
                    job_id, "system", f"Failed to run VRAM estimation container: {e}"
                )
                return
            
            if result.returncode != 0:
                reason = result.stderr.strip() or f"VRAM estimation exited with code {result.returncode}"
                logger.error("VRAM estimation failed for job %s: %s", job_id, reason)
                self._record_job(job_id, image_name, "vram_estimation", "failed", started_at)
                self.api.mark_job_failed(job_id, "user", reason)
                return
            
            try:
                with open(report_path, encoding="utf-8") as report_file:
                    report = json.load(report_file)
                if report.get("step_wall_time") is None:
                    raise ValueError("No optimizer steps were observed")
            except (OSError, ValueError, json.JSONDecodeError) as e:
                logger.error("Invalid VRAM estimation report for job %s: %s", job_id, e)
                self._record_job(job_id, image_name, "vram_estimation", "failed", started_at)
                self.api.mark_job_failed(
                    job_id, "user", f"Invalid VRAM estimation report: {e}"
                )
                return

        self.api.save_vram_estimation(job_id, report)
        self._record_job(
            job_id, image_name, "vram_estimation", "completed",
            started_at, round(report.get("peak_reserved_memory", 0.0), 2),
        )

    def handle_training(self, job_id: str, image_name: str):
        started_at = time.time()
        logger.info("Training job received for job %s.", job_id)
        record_event("info", f"Job {job_id} training started")

        job_output_dir = os.path.join(OUTPUT_DIR, job_id)
        # Start from a clean slate: a leftover dir could hold stale files from a
        # previous attempt that never got cleaned up.
        self._remove_output_dir(job_output_dir)
        os.makedirs(job_output_dir, exist_ok=True)

        mount_target, baseline = self._prepare_output_mount(job_output_dir, image_name)

        store = ObjectStore()
        monitor = OutputFileMonitor(job_id, job_output_dir, store, exclude=baseline)
        monitor.start()

        self._build_log_base = None
        self._last_log_upload = None
        self._log_push_buffer = []
        self._last_log_push = None
        self._job_log_buffer: list[str] = []

        self._run_container(
            job_id, image_name, job_output_dir, mount_target, store,
            monitor, started_at,
        )

    def handle_retry(self, job_id: str, image_name: str,
                     resume_command: str | None, original_command: str | None):
        started_at = time.time()
        logger.info("Retry job received for job %s.", job_id)
        record_event("info", f"Job {job_id} retry started")

        job_output_dir = os.path.join(OUTPUT_DIR, job_id)
        store = ObjectStore()

        # First try to pick up where the last run left off: restore the saved
        # checkpoints from the object store and run the resume command.
        if resume_command:
            resume_result = self._resume_attempt(
                job_id, image_name, job_output_dir, store,
                resume_command, started_at,
            )
            if resume_result is None:
                return

            failure_type, failure_reason = resume_result
            if failure_type == "system":
                # The resume container could not even start (infra issue, e.g.
                # busy GPU / docker daemon) — not a checkpoint problem, so a
                # fresh run would just burn GPU time and fail the same way.
                # Requeue via the normal failure path instead.
                logger.error("Job %s: resume could not start (%s).",
                             job_id, failure_reason)
                self._record_job(job_id, image_name, "training", "failed", started_at)
                self.api.mark_job_failed(job_id, failure_type, failure_reason)
                clear_running_job()
                return

            logger.warning(
                "Job %s: resume with restored checkpoints failed (%s); starting fresh.",
                job_id, failure_type,
            )

        # Resume failed (e.g. corrupted checkpoints) or there is no resume
        # command — discard everything and run the original training command
        # from scratch. If that fails too, it is a genuine code error and the
        # job is marked FAILED normally.
        if not original_command:
            logger.error("Job %s needs an original command to start fresh.", job_id)
            self._record_job(job_id, image_name, "training", "failed", started_at)
            self.api.mark_job_failed(
                job_id, "system", "Retry job has no original command"
            )
            clear_running_job()
            return

        logger.info("Job %s: starting fresh training run.", job_id)
        record_event("info", f"Job {job_id} starting fresh training run")
        self.handle_training(job_id, image_name)

    def _resume_attempt(self, job_id: str, image_name: str,
                        job_output_dir: str, store: ObjectStore,
                        resume_command: str, started_at: float):
        """Try to continue a job from its last checkpoints.

        If the output dir from a previous run is still on disk (this worker
        crashed and restarted), reuse those local checkpoints directly instead
        of re-uploading them to the object store and downloading them back. Only
        when there is no usable local state (a retry pulled from the scheduler,
        or a crash before the workspace baseline was recorded) does it seed the
        workspace and restore the last saved outputs from the object store.

        Returns None if the resumed run completed successfully, or a
        (failure_type, failure_reason) tuple if it failed, in which case the
        caller decides whether to discard the restored outputs and start fresh.
        """
        local_baseline = os.path.isfile(os.path.join(job_output_dir, META_FILE))
        if local_baseline:
            mount_target = self._resolve_mount_target(image_name) or CONTAINER_OUTPUT_MOUNT
            baseline = load_baseline(job_output_dir)
            baseline.add(os.path.join(job_output_dir, META_FILE))
            logger.info(
                "Job %s: resuming from local checkpoints in %s",
                job_id, job_output_dir,
            )
        else:
            self._remove_output_dir(job_output_dir)
            os.makedirs(job_output_dir, exist_ok=True)

            mount_target, baseline = self._prepare_output_mount(job_output_dir, image_name)

            # Restore the checkpoints into the workspace after the baseline is
            # recorded, so only the image's baked-in files are excluded from
            # uploads and the resumed run's updated checkpoints still get pushed.
            self._restore_job_output(job_id, job_output_dir, store)

        monitor = OutputFileMonitor(job_id, job_output_dir, store, exclude=baseline)
        monitor.start()

        self._build_log_base = None
        self._last_log_upload = None
        self._log_push_buffer = []
        self._last_log_push = None
        self._job_log_buffer: list[str] = []

        success, failure_type, failure_reason = self._run_container(
            job_id, image_name, job_output_dir, mount_target, store,
            monitor, started_at,
            command_args=["sh", "-c", resume_command],
            finalize=False,
        )

        if success:
            logger.info("Job %s: resumed successfully.", job_id)
            self._finalize_job(job_id, image_name, job_output_dir, monitor,
                               started_at, True)
            return None

        logger.error("Job %s: resume failed (%s: %s).",
                     job_id, failure_type, failure_reason)
        self._remove_output_dir(job_output_dir)
        return failure_type, failure_reason

    def _restore_job_output(self, job_id: str, job_output_dir: str, store: ObjectStore):
        """Download the job's previously uploaded outputs from the object store
        into the container's workspace."""
        objects = store.list_objects(prefix=f"{job_id}/")
        restored = 0
        for obj in objects:
            key = obj.get("key", "")
            rel_path = key[len(job_id) + 1:] if key.startswith(f"{job_id}/") else key
            if not rel_path:
                continue
            # build.log is a build artifact, not training state; skip it.
            if os.path.basename(rel_path) == "build.log":
                continue

            dest = os.path.join(job_output_dir, rel_path)
            if store.download_to(key, dest, size=obj.get("size")):
                restored += 1
            else:
                logger.warning(
                    "Job %s: failed to restore %s from object store.", job_id, key
                )

        if objects:
            logger.info("Job %s: restored %d/%d file(s) from object store.",
                        job_id, restored, len(objects))
        else:
            logger.info("Job %s: no previously saved outputs to restore.", job_id)

    def _run_container(self, job_id: str, image_name: str,
                              job_output_dir: str, mount_target: str,
                              store: ObjectStore, monitor: OutputFileMonitor,
                              started_at: float, command_args: list[str] | None = None,
                              finalize: bool = True):
        cmd = [
            "docker", "run", "--rm", "--gpus", "all",
            *self._container_user_args(),
            "-v", f"{_docker_host_path(job_output_dir)}:{mount_target}",
            image_name,
        ]
        if command_args:
            cmd.extend(command_args)
        logger.info("Running container: %s", " ".join(cmd))

        success = False
        failure_type = "system"
        failure_reason = "Training container failed to start"
        try:
            proc = subprocess.Popen(
                cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                text=True, bufsize=1,
            )

            for line in iter(proc.stdout.readline, ""):
                line = line.rstrip("\r\n")
                self._job_log_buffer.append(line)
                self._log_push_buffer.append(line)
                self._flush_log_push(job_id)
                logger.info("[job %s] %s", job_id, line)

                if time.monotonic() - (self._last_log_upload or 0) >= runtime_config.get("log_upload_interval"):
                    self._append_build_log(job_id, store, self._job_log_buffer)

            proc.wait()
            success = proc.returncode == 0
            if not success:
                failure_type = "user"
                failure_reason = f"Training command exited with code {proc.returncode}"
        except Exception as e:
            failure_type = "system"
            failure_reason = f"Execution error: {e}"
            logger.error("Execution error for job %s: %s", job_id, e)

        self._flush_log_push(job_id, force=True)
        self._append_build_log(job_id, store, self._job_log_buffer, force=True)
        monitor.stop()

        if not finalize:
            return success, failure_type, failure_reason

        self._finalize_job(job_id, image_name, job_output_dir, monitor,
                           started_at, success, failure_type, failure_reason)

    def _remove_output_dir(self, job_output_dir: str) -> bool:
        """Delete a job output dir, falling back to a root docker helper when
        it contains files/dirs owned by the container's root user."""
        shutil.rmtree(job_output_dir, ignore_errors=True)
        if not os.path.exists(job_output_dir):
            return True
        try:
            subprocess.run(
                [
                    "docker", "run", "--rm",
                    "-v", f"{_docker_host_path(job_output_dir)}:/cleanup",
                    "alpine", "rm", "-rf", "/cleanup",
                ],
                check=True, capture_output=True, text=True, timeout=180,
            )
            return not os.path.exists(job_output_dir)
        except Exception as e:
            logger.warning("Docker-assisted cleanup failed for %s: %s",
                           job_output_dir, e)
            return False

    def _finalize_job(self, job_id: str, image_name: str, job_output_dir: str,
                      monitor: OutputFileMonitor, started_at: float,
                      success: bool, failure_type: str = "system",
                      failure_reason: str = ""):
        monitor.flush()
        pending = monitor.pending_uploads()
        if pending:
            logger.warning(
                "Job %s: %d file(s) failed to upload to object store; "
                "keeping output dir at %s",
                job_id, len(pending), job_output_dir,
            )
        elif self._remove_output_dir(job_output_dir):
            logger.info("Deleted output directory for job %s.", job_id)
        else:
            logger.warning("Could not fully delete output dir for job %s: %s",
                           job_id, job_output_dir)

        if success:
            logger.info("Job %s completed successfully.", job_id)
            self.api.mark_job_completed(job_id)
            self._record_job(job_id, image_name, "training", "completed", started_at)
        else:
            logger.error("Job %s failed.", job_id)
            self._record_job(job_id, image_name, "training", "failed", started_at)
            self.api.mark_job_failed(job_id, failure_type, failure_reason)

        clear_running_job()

    def _flush_log_push(self, job_id: str, force: bool = False):
        if not self._log_push_buffer:
            return

        now = time.monotonic()
        if (
            not force
            and self._last_log_push is not None
            and (now - self._last_log_push) < runtime_config.get("log_push_interval")
        ):
            return

        lines = self._log_push_buffer
        self._log_push_buffer = []
        self.api.send_logs(job_id, lines)
        self._last_log_push = now

    def _append_build_log(
        self, job_id: str, store: ObjectStore, log_buffer: list[str], force: bool = False
    ):
        if not log_buffer:
            return

        now = time.monotonic()
        if (
            not force
            and self._last_log_upload is not None
            and (now - self._last_log_upload) < runtime_config.get("log_upload_interval")
        ):
            return

        if self._build_log_base is None:
            existing = store.download(f"{job_id}/build.log")
            self._build_log_base = (
                existing.decode("utf-8", errors="replace") if existing else ""
            )

        content = self._build_log_base
        if content and not content.endswith("\n"):
            content += "\n"
        content += "\n".join(log_buffer) + "\n"

        if store.upload_bytes(
            f"{job_id}/build.log", content.encode("utf-8"), "text/plain"
        ):
            self._last_log_upload = now

    def handle_interactive(self, job: dict):
        """Deploy an interactive two-container session (env + access)."""
        import interactive_handler

        session_id = job.get("session_id")
        if not session_id:
            logger.error("Interactive job payload missing session_id.")
            return
        interactive_handler.run_interactive_session(
            self.api,
            session_id,
            job.get("env_image_tag", ""),
            job.get("access_image_tag", ""),
            job.get("headscale_url", ""),
            job.get("headscale_auth_key", ""),
            job.get("ssh_public_key", ""),
        )

    def process_job(self, job: dict):
        flag = job.get("flag", "training")
        if flag == "interactive":
            self.handle_interactive(job)
            return

        job_id = job.get("job_id") or job.get("id")
        image_name = f"{DOCKER_HUB_USERNAME}/{job_id}:latest"

        if not self.pull_docker_image(image_name):
            logger.error("Aborting job %s: image pull failed.", job_id)
            self.api.mark_job_failed(
                job_id, "system", f"Failed to pull Docker image {image_name}"
            )
            return

        if flag == "vram_estimation":
            self.handle_vram_estimation(job_id, image_name, job.get("command", ""))
        elif flag == "training":
            save_running_job(job_id)
            self.handle_training(job_id, image_name)
        elif flag == "retry":
            save_running_job(job_id)
            self.handle_retry(job_id, image_name, job.get("resume_command"),
                              job.get("command"))
        else:
            logger.warning("Unknown job flag '%s' for job %s.", flag, job_id)

    def resume_persisted_job_if_any(self) -> bool:
        """Pick up a job this worker was running before it died, if the scheduler
        still has it IN_PROGRESS on this worker.

        The scheduler only requeues a job (RETRY_NEEDED) after the worker has
        missed heartbeats for several minutes, so a worker that comes back sooner
        would otherwise leave the job stuck IN_PROGRESS with nothing running it.
        The persisted marker lets the restarted worker resume it (restoring the
        last checkpoints and running the resume command, falling back to a fresh
        run if the resume fails).
        """
        state = load_running_job()
        if not state:
            return False

        job_id = state.get("job_id")
        if not job_id:
            clear_running_job()
            return False

        try:
            gpu_type, _, _, _, _ = get_gpu_info()
            job = self.api.resume_job(job_id, gpu_type)
        except Exception as e:
            logger.warning("Could not contact scheduler to resume job %s; "
                           "will retry later.", job_id)
            return False

        if job is None:
            logger.info("Job %s is no longer in progress on this worker; "
                        "dropping local resume state.", job_id)
            clear_running_job()
            return False

        image_name = f"{DOCKER_HUB_USERNAME}/{job_id}:latest"
        logger.info("Resuming persisted job %s after worker restart.", job_id)
        record_event("info", f"Resuming persisted job {job_id} after worker restart")

        if not self.pull_docker_image(image_name):
            logger.error("Aborting resume of job %s: image pull failed.", job_id)
            clear_running_job()
            return False

        self.handle_retry(job_id, image_name, job.get("resume_command"),
                          job.get("command"))
        return True