import json
import os
import threading
import time
import logging

from object_store import ObjectStore

logger = logging.getLogger("output_monitor")

# Marker file stored inside each job's output dir recording the paths of the
# image's baked-in files that were seeded into the workspace. Those files are
# never uploaded to the object store; the marker lets a restarted worker reuse
# a leftover output dir (resume from local checkpoints) while excluding the
# image's own files from uploads.
META_FILE = ".output_baseline"


def write_baseline(job_output_dir: str, baseline: set[str]):
    """Persist the seeded (baked-in) file paths so a restarted worker can
    distinguish them from files generated by the running code."""
    rel_paths = sorted(os.path.relpath(p, job_output_dir) for p in baseline)
    meta_path = os.path.join(job_output_dir, META_FILE)
    tmp_path = meta_path + ".tmp"
    try:
        with open(tmp_path, "w", encoding="utf-8") as f:
            json.dump(rel_paths, f)
        os.replace(tmp_path, meta_path)
    except OSError as e:
        logger.warning("Failed to persist baseline for %s: %s", job_output_dir, e)


def load_baseline(job_output_dir: str) -> set[str]:
    meta_path = os.path.join(job_output_dir, META_FILE)
    try:
        with open(meta_path, "r", encoding="utf-8") as f:
            rel_paths = json.load(f)
        return {os.path.join(job_output_dir, p) for p in rel_paths}
    except (OSError, ValueError, TypeError):
        return set()


class OutputFileMonitor(threading.Thread):
    """Watches a job's output directory and uploads new/changed files to the object store."""

    def __init__(
        self,
        job_id: str,
        output_dir: str,
        store: ObjectStore,
        poll_interval: float = 2.0,
        exclude: set[str] | None = None,
    ):
        super().__init__(daemon=True)
        self.job_id = job_id
        self.output_dir = output_dir
        self.store = store
        self.poll_interval = poll_interval
        self._exclude = exclude or set()
        self._stop_event = threading.Event()
        self._uploaded: dict[str, tuple[int, float]] = {}
        self._lock = threading.Lock()

    def run(self):
        while not self._stop_event.is_set():
            self._scan()
            time.sleep(self.poll_interval)

    def stop(self, retries: int = 3, retry_delay: float = 0.5):
        self._stop_event.set()
        self.join()
        self.flush(retries=retries, retry_delay=retry_delay)

    def flush(self, retries: int = 3, retry_delay: float = 0.5):
        """Final scan, retrying until all files are uploaded (or attempts exhausted)."""
        for attempt in range(retries):
            self._scan()
            if attempt < retries - 1:
                time.sleep(retry_delay)

    def _scan(self):
        if not os.path.isdir(self.output_dir):
            return
        for root, _dirs, files in os.walk(self.output_dir):
            for name in files:
                self._maybe_upload(os.path.join(root, name))

    def pending_uploads(self) -> list[str]:
        """Paths still on disk that have not been successfully uploaded."""
        if not os.path.isdir(self.output_dir):
            return []
        pending = []
        for root, _dirs, files in os.walk(self.output_dir):
            for name in files:
                path = os.path.join(root, name)
                if path in self._exclude:
                    continue
                object_key = f"{self.job_id}/{os.path.relpath(path, self.output_dir)}"
                with self._lock:
                    if object_key in self._uploaded:
                        continue
                pending.append(path)
        return pending

    def _maybe_upload(self, file_path: str):
        if file_path in self._exclude:
            return
        try:
            stat = os.stat(file_path)
        except OSError:
            return

        object_key = f"{self.job_id}/{os.path.relpath(file_path, self.output_dir)}"
        signature = (stat.st_size, stat.st_mtime)

        with self._lock:
            if self._uploaded.get(object_key) == signature:
                return

        if self.store.upload_file(object_key, file_path):
            with self._lock:
                self._uploaded[object_key] = signature
