import json
import os
import shutil
import threading
import time
import logging

from object_store import ObjectStore

logger = logging.getLogger("output_monitor")

# Marker file stored inside each job's output dir recording the paths of the
# image's baked-in files that were seeded into the workspace. Those files are
# never uploaded to the object store; the marker lets a restarted worker skip
# them too when recovering leftover outputs.
META_FILE = ".output_baseline"


def write_baseline(job_output_dir: str, baseline: set[str]):
    """Persist the seeded (baked-in) file paths so a restarted worker can
    distinguish them from files generated by the running code."""
    rel_paths = sorted(os.path.relpath(p, job_output_dir) for p in baseline)
    meta_path = os.path.join(job_output_dir, META_FILE)
    tmp_path = meta_path + ".tmp"
    try:
        with open(tmp_path, "w", encoding="utf-8") as f:
            json.dump(rel_paths, f)
        os.replace(tmp_path, meta_path)
    except OSError as e:
        logger.warning("Failed to persist baseline for %s: %s", job_output_dir, e)


def load_baseline(job_output_dir: str) -> set[str]:
    meta_path = os.path.join(job_output_dir, META_FILE)
    try:
        with open(meta_path, "r", encoding="utf-8") as f:
            rel_paths = json.load(f)
        return {os.path.join(job_output_dir, p) for p in rel_paths}
    except (OSError, ValueError, TypeError):
        return set()


def recover_job_outputs(output_dir: str, store: ObjectStore) -> int:
    """Upload leftover job outputs left on disk by a previous run to the object
    store, deleting each local file once it has been uploaded.

    Runs at worker startup so results survive a graceful shutdown or crash that
    interrupted the normal upload-and-cleanup path. Only job dirs carrying a
    baseline marker are processed, since the marker is what distinguishes
    generated files from the image's seeded source; a dir without one could
    contain source files and is left untouched. Files that fail to upload are
    left on disk to be retried on the next start. Returns the number of files
    uploaded.
    """
    if not os.path.isdir(output_dir):
        return 0
    total = 0
    for job_id in os.listdir(output_dir):
        job_dir = os.path.join(output_dir, job_id)
        if not os.path.isdir(job_dir):
            continue
        meta_path = os.path.join(job_dir, META_FILE)
        if not os.path.exists(meta_path):
            logger.warning(
                "Recovery: skipping %s — no %s marker, refusing to upload "
                "unverified files (may include seeded source). Remove the dir "
                "manually if it holds no results.",
                job_dir, META_FILE,
            )
            continue
        baseline = load_baseline(job_dir)
        uploaded = 0
        pending = 0
        for root, _dirs, files in os.walk(job_dir):
            for name in files:
                path = os.path.join(root, name)
                if path in baseline or path == meta_path:
                    continue
                rel_path = os.path.relpath(path, job_dir)
                if store.upload_file(f"{job_id}/{rel_path}", path):
                    try:
                        os.remove(path)
                        uploaded += 1
                    except OSError as e:
                        logger.warning(
                            "Recovery: uploaded %s but failed to delete it locally: %s",
                            path, e,
                        )
                else:
                    pending += 1
        if pending == 0:
            shutil.rmtree(job_dir, ignore_errors=True)
            logger.info(
                "Recovery: uploaded %d leftover file(s) for job %s; removed output dir.",
                uploaded, job_id,
            )
        else:
            logger.warning(
                "Recovery: uploaded %d/%d leftover file(s) for job %s; "
                "%d remain on disk to retry next start.",
                uploaded, uploaded + pending, job_id, pending,
            )
        total += uploaded
    return total


class OutputFileMonitor(threading.Thread):
    """Watches a job's output directory and uploads new/changed files to the object store."""

    def __init__(
        self,
        job_id: str,
        output_dir: str,
        store: ObjectStore,
        poll_interval: float = 2.0,
        exclude: set[str] | None = None,
    ):
        super().__init__(daemon=True)
        self.job_id = job_id
        self.output_dir = output_dir
        self.store = store
        self.poll_interval = poll_interval
        self._exclude = exclude or set()
        self._stop_event = threading.Event()
        self._uploaded: dict[str, tuple[int, float]] = {}
        self._lock = threading.Lock()

    def run(self):
        while not self._stop_event.is_set():
            self._scan()
            time.sleep(self.poll_interval)

    def stop(self, retries: int = 3, retry_delay: float = 0.5):
        self._stop_event.set()
        self.join()
        self.flush(retries=retries, retry_delay=retry_delay)

    def flush(self, retries: int = 3, retry_delay: float = 0.5):
        """Final scan, retrying until all files are uploaded (or attempts exhausted)."""
        for attempt in range(retries):
            self._scan()
            if attempt < retries - 1:
                time.sleep(retry_delay)

    def _scan(self):
        if not os.path.isdir(self.output_dir):
            return
        for root, _dirs, files in os.walk(self.output_dir):
            for name in files:
                self._maybe_upload(os.path.join(root, name))

    def pending_uploads(self) -> list[str]:
        """Paths still on disk that have not been successfully uploaded."""
        if not os.path.isdir(self.output_dir):
            return []
        pending = []
        for root, _dirs, files in os.walk(self.output_dir):
            for name in files:
                path = os.path.join(root, name)
                if path in self._exclude:
                    continue
                object_key = f"{self.job_id}/{os.path.relpath(path, self.output_dir)}"
                with self._lock:
                    if object_key in self._uploaded:
                        continue
                pending.append(path)
        return pending

    def _maybe_upload(self, file_path: str):
        if file_path in self._exclude:
            return
        try:
            stat = os.stat(file_path)
        except OSError:
            return

        object_key = f"{self.job_id}/{os.path.relpath(file_path, self.output_dir)}"
        signature = (stat.st_size, stat.st_mtime)

        with self._lock:
            if self._uploaded.get(object_key) == signature:
                return

        if self.store.upload_file(object_key, file_path):
            with self._lock:
                self._uploaded[object_key] = signature
